"""inti

Revision ID: e7f0d165972f
Revises: 
Create Date: 2024-08-24 04:19:11.941497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f0d165972f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('fid', sa.String(length=36), nullable=False, comment='Code file storing the file.'),
    sa.Column('filename', sa.String(length=256), nullable=True, comment='Name of uploaded file'),
    sa.PrimaryKeyConstraint('fid'),
    sa.UniqueConstraint('fid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    # ### end Alembic commands ###
